name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # - name: configure
      # run: ./configure
    - name: make build
      run: make build
    - name: run
      run: make run
    # - name: make check
      # run: make check
    # - name: make distcheck
      # run: make distcheck
